definitions:
  model.Tag:
    properties:
      create:
        type: integer
      id:
        type: string
      last:
        type: integer
      name:
        type: string
      uid:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/pub/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user info for login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.Tag'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MjgwMTY5MjIsImlkIjowLCJuYmYiOjE1MjgwMTY5MjIsInVzZXJuYW1lIjoiYWRtaW4ifQ.LjxrK9DuAwAzUD8-9v43NzWBN7HXsSLfebw92DKd1JQ"}}'
          schema:
            type: string
      summary: Login generates the authentication token
      tags:
      - user
  /signup:
    post:
      consumes:
      - application/json
      description: Add a new user
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: object
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"username":"kong"}}'
          schema:
            type: string
      summary: SignUp a new user
      tags:
      - user
swagger: "2.0"
